#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements
if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root."
    exit 1
fi

echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts

echo "Configuration completed. Updated /etc/hosts file:"
cat /etc/hosts

