#!/usr/bin/env bash
#script that make nginx as nginx user
pkill apache
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sed -i 's/# user www-data/user nginx/g' /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
